### ISSUE TITLE
HTTP error [503] while uploading file to Auger Cloud...

### ISSUE THREAD

**Issue by IgorFlint** [deeplearninc/auger-ai#6]
Having
$ augerai dataset list:
```
iris.csv
1 DataSet(s) listed
```
$ augerai dataset create
led me to
```
Starting Project to process request...
Cluster status is provisioning...
Cluster status is bootstrapping...
Cluster status is running...
Project status is deploying...
Project status is deployed...
Project status is running...
Traceback (most recent call last):
  File "/home/flint/projects/deeplearninc/auger-ai/auger/cli/utils/decorators.py", line 9, in wrapper
    return decorated(self, *args, **kwargs)
  File "/home/flint/projects/deeplearninc/auger-ai/auger/cli/utils/decorators.py", line 22, in wrapper
    return decorated(self, *args, **kwargs)
  File "/home/flint/projects/deeplearninc/auger-ai/auger/cli/utils/decorators.py", line 45, in wrapper
    return decorated(self, project, *args, **kwargs)
  File "/home/flint/projects/deeplearninc/auger-ai/auger/cli/commands/cmd_dataset.py", line 30, in create
    dataset = DataSet(self.ctx, project).create(source)
  File "/home/flint/projects/deeplearninc/auger-ai/auger/api/dataset.py", line 20, in create
    super().create(data_source_file, data_set_name)
  File "/home/flint/projects/deeplearninc/auger-ai/auger/api/hub/data_set.py", line 30, in create
    file_url = self._upload_to_hub(data_source_file)
  File "/home/flint/projects/deeplearninc/auger-ai/auger/api/hub/data_set.py", line 77, in _upload_to_hub
    return self._upload_to_single_tenant(file_to_upload)
  File "/home/flint/projects/deeplearninc/auger-ai/auger/api/hub/data_set.py", line 94, in _upload_to_single_tenant
    file_url = self._upload_file(file_to_upload, upload_url)
  File "/home/flint/projects/deeplearninc/auger-ai/auger/api/hub/data_set.py", line 108, in _upload_file
    'HTTP error [%s] while uploading file to Auger Cloud...' % r.status_code)
auger.api.hub.utils.exception.AugerException: HTTP error [503] while uploading file to Auger Cloud...
HTTP error [503] while uploading file to Auger Cloud...
```

Another try right after the first one:
$ augerai dataset create
```
Uploaded local file to Auger Cloud file: files/8b8e2729cd92ea410607a952d2f41bf651eafe16
Data Set status is processing...
Data Set status is processed...
Created DataSet iris-1.csv
```
Having now:
```
$ augerai dataset list
iris-1.csv
iris.csv
2 DataSet(s) listed
```

It may be related to name clashing. Need to investigate further.

**Comment by vlad-dplrn** [comment]
fixed on HUB, closing for now
